"""Make the chained tables' `seq` GENERATED ALWAYS rather than BY DEFAULT.

`generated by default as identity` lets any caller supply its own `seq` on
INSERT. That matters here because INSERT is precisely the privilege `uc3_app`
holds: one row written with a very large `seq` sorts after every append that
follows it, so each later row's `prev_hash` points at the wrong predecessor and
`chain_verify` reports a break for every one of them.

The damage is permanent. Repairing it means deleting or renumbering the planted
row, and 0008 revoked UPDATE and DELETE from the same role -- so the least
privileged credential in the system can destroy the audit trail's integrity and
nobody short of a superuser can put it back. `generated always` closes it: the
database refuses a client-supplied value outright, and the application never
supplies one.

Separate revision rather than an edit to 0007 because a revision that has left
the branch is immutable, and the repo hooks enforce that.
"""

from alembic import op

revision = "0010_uc3_seq_generated_always"
down_revision = "0009_uc3_chain_anchor"
branch_labels = None
depends_on = None

CHAINED = ("analysis_runs", "flags", "dispositions")
ROLE = "uc3_app"
ANCHOR = "audit_chain_anchors"


def upgrade() -> None:
    for table in CHAINED:
        op.execute(f"alter table {table} alter column seq set generated always;")

    # 0009 created the anchor and granted `uc3_app` nothing on it, so the app
    # role cannot reach it. But "nothing was granted" is a default, and the
    # anchor is what detects a truncated tail -- a control resting on an
    # installation default rather than on a statement is one nobody can audit
    # by reading the migrations. Say it.
    op.execute(f"revoke all on table {ANCHOR} from {ROLE};")
    op.execute(f"revoke all on table {ANCHOR} from public;")


def downgrade() -> None:
    for table in CHAINED:
        op.execute(f"alter table {table} alter column seq set generated by default;")
    # The revokes are not reversed: see 0008 for why a downgrade that widens
    # write access is the worse failure mode.
